services:
  web:
    image: ghcr.io/wallet-ui/wallet-ui-astro:latest
    pull_policy: always
    environment:
      - SPA=false
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
