const legacyRedirects = {
	'/docs': '/react/getting-started',
	'/docs/core': '/core',
	'/docs/core/clusters': '/core/clusters',
	'/docs/core/storage': '/core/storage',
	'/docs/core/utilities': '/core/utilities',
	'/docs/react': '/react/getting-started',
	'/docs/react-native/kit/core-concepts': '/react-native/kit/core-concepts',
	'/docs/react-native/kit/getting-started': '/react-native/kit/getting-started',
	'/docs/react-native/kit/guides/expo': '/react-native/kit/guides/expo',
	'/docs/react-native/kit/hooks': '/react-native/kit/hooks',
	'/docs/react-native/kit/hooks/use-authorization': '/react-native/kit/hooks/use-authorization',
	'/docs/react-native/kit/hooks/use-mobile-wallet': '/react-native/kit/hooks/use-mobile-wallet',
	'/docs/react-native/kit/providers': '/react-native/kit/providers',
	'/docs/react-native/web3js/core-concepts': '/react-native/web3js/core-concepts',
	'/docs/react-native/web3js/getting-started': '/react-native/web3js/getting-started',
	'/docs/react-native/web3js/guides/expo': '/react-native/web3js/guides/expo',
	'/docs/react-native/web3js/hooks': '/react-native/web3js/hooks',
	'/docs/react-native/web3js/hooks/use-authorization': '/react-native/web3js/hooks/use-authorization',
	'/docs/react-native/web3js/hooks/use-mobile-wallet': '/react-native/web3js/hooks/use-mobile-wallet',
	'/docs/react-native/web3js/providers': '/react-native/web3js/providers',
	'/docs/react/components': '/react/components',
	'/docs/react/components/account-guard': '/react/components/account-guard',
	'/docs/react/components/cluster-dropdown': '/react/components/cluster-dropdown',
	'/docs/react/components/dropdown': '/react/components/dropdown',
	'/docs/react/core-concepts': '/react/core-concepts',
	'/docs/react/getting-started': '/react/getting-started',
	'/docs/react/guides/next': '/react/guides/next',
	'/docs/react/guides/react-router': '/react/guides/vite',
	'/docs/react/guides/vite': '/react/guides/vite',
	'/docs/react/hooks': '/react/hooks',
	'/docs/react/hooks/use-wallet-ui': '/react/hooks/use-wallet-ui',
	'/docs/react/hooks/use-wallet-ui-account': '/react/hooks/use-wallet-ui-account',
	'/docs/react/hooks/use-wallet-ui-cluster': '/react/hooks/use-wallet-ui-cluster',
	'/docs/react/hooks/use-wallet-ui-dropdown': '/react/hooks/use-wallet-ui-dropdown',
	'/docs/react/hooks/use-wallet-ui-sign-and-send': '/react/hooks/use-wallet-ui-sign-and-send',
	'/docs/react/hooks/use-wallet-ui-signer': '/react/hooks/use-wallet-ui-signer',
	'/docs/react/hooks/use-wallet-ui-wallet': '/react/hooks/use-wallet-ui-wallet',
	'/docs/react/hooks/use-wallet-ui-wallets': '/react/hooks/use-wallet-ui-wallets',
	'/docs/react/providers': '/react/providers',
	'/docs/react/providers/wallet-ui-account-context': '/react/providers/wallet-ui-account-context',
	'/docs/react/providers/wallet-ui-account-context-provider': '/react/providers/wallet-ui-account-context-provider',
	'/docs/react/providers/wallet-ui-cluster-context': '/react/providers/wallet-ui-cluster-context',
	'/docs/react/providers/wallet-ui-cluster-context-provider': '/react/providers/wallet-ui-cluster-context-provider',
	'/docs/react/providers/wallet-ui-context': '/react/providers/wallet-ui-context',
	'/docs/react/providers/wallet-ui-context-provider': '/react/providers/wallet-ui-context-provider',
	'/docs/react/styling': '/react/styling',
	'/docs/react/styling/css': '/react/styling/css',
	'/docs/react/styling/tailwind': '/react/styling/tailwind',
};

export const redirects = {
	...legacyRedirects,
	'/guides/astro-migration': '/',
	'/guides/choose-your-sdk': '/',
	'/react/guides/react-router': '/react/guides/vite',
};
